# Generated by Django 2.0.5 on 2018-05-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_job_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cl_duration',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='job',
            name='cl_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='cl_intensity',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='job',
            name='dead',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='job',
            name='elasticity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='layerHeight',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='job',
            name='layerNum',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='job',
            name='live',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='job',
            name='pressure1',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='job',
            name='pressure2',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='job',
            name='wellplate',
            field=models.IntegerField(default=-1),
        ),
    ]
